<Project>
  <PropertyGroup>
    <Authors>Aurelia Community</Authors>
    <LangVersion>latest</LangVersion>
    <Version>0.17.0</Version>
    <Copyright>Copyright (c) 2026 Hasan Ismail and Aurelia contributors</Copyright>
    <PackageLicenseExpression>AGPL-3.0-or-later</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/hasan-ismail/Aurelia</PackageProjectUrl>
  </PropertyGroup>
</Project>